name: Deploy - lab 14

on:
  workflow_dispatch: # uruchamianie ręczne

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Buildx set-up
        uses: docker/setup-buildx-action@v2

        # logowanie do dockerhuba
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
        # zbudowanie obrazu i wrzucenie go na repo dockerhuba
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: ./
          push: true
          tags: |
            voiteckheir/tch-lab14:eb_frontend

        # wygenerowanie paczki do deployu, domyślnie używa zipa,
      - name: Generate deployment package
        run: zip -r deploy.zip . -x '*.git*'
        #run: zip deploy.zip ./docker-compose.yml

        # deploy na aws elastic beanstalk używamy sekretów z 'bota' tórego uprzednio tworzymy jako nowegu usera w IAM
      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v21
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: zadanie14 # nazwa aplikacji na aws generowana wcześniej komendami eb init
          environment_name: zadanie14-env # nazwa środowiska na aws

          version_label: 667
          region: us-east-1 # region na którym jest główne konto i bot
          deployment_package: deploy.zip # nazwa paczki do deployu wygenerowana wcześniej
